apiVersion: 1.0.0                              

previews:
  - name: insurance-frontend
    container:
      image: gcr.io/core-flow-research/insurancehive/insurance-frontend:${{env.commit.sha}}
      ports:
      - value: 80